"""Tests for the experiment-14 statistical-test pipeline (GOAL.md section 18).

All tests run fully offline on small synthetic fixtures:

* Wilson CI endpoints are checked against hand-computed closed-form values
  and one literature anchor (wilson_ci(25, 100), the statsmodels/R
  ``prop.test`` value already used by ``test_metrics.py``).
* The paired bootstrap is verified to be *paired*: replicating the seed's
  index stream and differencing the two systems per replicate must reproduce
  every stored ΔAURC / ΔAUGRC value exactly.
* McNemar b/c counts and the exact-binomial p-value are checked against
  hand-derived values (b=4, c=1 → p = 2 * P(X ≤ 1; n=5, .5) = 0.375).
* Missing inputs are hard errors (no silent skips).

The experiment-13 outputs used for cross-checking are generated by the real
``run_selective_inference`` machinery (``exact_curve`` /
``goal13_metric_rows``) on the same fixture runs, so the cross-check is
exercised end-to-end.
"""

from __future__ import annotations

import csv
import hashlib
import json
import math
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np
import pytest

TESTS_DIR = Path(__file__).resolve().parent
CODE_DIR = TESTS_DIR.parent
for _p in (str(CODE_DIR), str(CODE_DIR / "independent_eval")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from experiment_pipelines import run_statistical_tests as rst
from experiment_pipelines import run_selective_inference as rsi
from independent_eval import metrics
from independent_eval._common import derive_seed
from independent_eval.manifest import MANIFEST_FIELDS

N_REPLICATES = 24

RUNS_FIELDS = [
    "sample_id",
    "task_type",
    "item_id",
    "split",
    "method_id",
    "method_name",
    "evidence_class",
    "comparison_tier",
    "overlap_status",
    "primary_comparison_eligible",
    "evaluation_eligibility",
    "availability_status",
    "gold_label",
    "prediction",
    "confidence",
    "covered",
    "correct",
    "hard_constraint_pass",
    "constraint_gate_source",
    "safe_correct",
    "actual_llm_calls",
    "source_artifact",
    "note",
]

N_ET = 16  # entity_type, scored (curve mode)
N_SA = 12  # scope_adjustment, point-only (no confidence by design §4.3)
N_PRV = 100  # provenance_support, blind LLM only (Wilson literature anchor)


def _base_row(sample_id: str, task_type: str, method_id: str, method_name: str) -> dict:
    return {
        "sample_id": sample_id,
        "task_type": task_type,
        "item_id": f"I-{sample_id}",
        "split": "independent_eval",
        "method_id": method_id,
        "method_name": method_name,
        "evidence_class": "actual_run",
        "comparison_tier": "independent_reference",
        "overlap_status": "independent_of_era",
        "primary_comparison_eligible": 1,
        "evaluation_eligibility": "core_eligible_task",
        "availability_status": "available",
        "gold_label": "",
        "prediction": "",
        "confidence": "",
        "covered": 1,
        "correct": 1,
        "hard_constraint_pass": 1,
        "constraint_gate_source": "synthetic gate",
        "safe_correct": 1,
        "actual_llm_calls": 0,
        "source_artifact": "synthetic",
        "note": "synthetic test row",
    }


def _entity_type_rows() -> list[dict]:
    """16 scored samples; errors placed last (Full), first (B1), middle (B2).

    ``correct = prediction == 'Event'`` with gold 'Event' everywhere.
    Full (B12) fails the hard gate on the last two samples; B10 (selective,
    no gate) shares B12's predictions with the gate disabled.  B9 carries a
    two-level agreement confidence (→ too few discrete scores for areas).
    """
    rows = []
    for index in range(N_ET):
        sample_id = f"ET-s{index + 1:02d}"
        confidence = f"{0.95 - 0.01 * index:.12f}"
        specs = [
            ("B12_full_framework", "Place" if index >= 12 else "Event",
             0 if index >= 14 else 1),
            ("B10_selective_no_gate", "Place" if index >= 12 else "Event", 1),
            ("B1_rule_only", "Place" if index < 4 else "Event", 1),
            ("B2_classifier_only", "Place" if 6 <= index <= 9 else "Event", 1),
            ("B9_agreement_gate", "Place" if index < 4 else "Event", 1),
        ]
        for method_id, prediction, gate in specs:
            row = _base_row(sample_id, "entity_type", method_id, METHOD_NAMES[method_id])
            row["gold_label"] = "Event"
            row["prediction"] = prediction
            row["confidence"] = (
                confidence
                if method_id != "B9_agreement_gate"
                else ("1.0" if index % 2 == 0 else "0.0")
            )
            row["correct"] = int(prediction == "Event")
            row["hard_constraint_pass"] = gate
            row["safe_correct"] = int(row["correct"] and gate)
            rows.append(row)
    return rows


def _scope_adjustment_rows() -> list[dict]:
    """12 point-only samples; B12 always predicts AFTER_BETTER (design §4.3).

    Reference: AFTER_BETTER on {0..6}, BEFORE_BETTER on {7..11}.  B3 agrees
    with the reference only on {0,1,2,8}, so the McNemar discordances are
    b = Full correct & B3 wrong = {3,4,5,6} = 4 and
    c = B3 correct & Full wrong = {8} = 1.
    """
    rows = []
    b3_after = {0, 1, 2, 7, 9, 10, 11}  # BEFORE_BETTER elsewhere (incl. 8)
    for index in range(N_SA):
        sample_id = f"SA-s{index + 1:02d}"
        reference = "AFTER_BETTER" if index <= 6 else "BEFORE_BETTER"
        b12_prediction = "AFTER_BETTER"
        b3_prediction = "AFTER_BETTER" if index in b3_after else "BEFORE_BETTER"
        for method_id, prediction in (
            ("B12_full_framework", b12_prediction),
            ("B3_blind_llm", b3_prediction),
        ):
            row = _base_row(sample_id, "scope_adjustment", method_id, METHOD_NAMES[method_id])
            row["prediction"] = prediction
            row["confidence"] = ""  # design §4.3: no graded confidence
            row["correct"] = int(prediction == reference)
            row["safe_correct"] = row["correct"]
            rows.append(row)
    return rows


def _provenance_rows() -> list[dict]:
    """Blind LLM only, 25/100 predictions available, 10 correct (no Full)."""
    rows = []
    for index in range(N_PRV):
        sample_id = f"PRV-s{index + 1:03d}"
        available = index < 25
        row = _base_row(sample_id, "provenance_support", "B3_blind_llm", METHOD_NAMES["B3_blind_llm"])
        row["availability_status"] = "available" if available else "not_available"
        row["prediction"] = "fully_supported" if available else ""
        row["hard_constraint_pass"] = 1 if available else 0
        row["correct"] = int(available and index < 10)
        row["safe_correct"] = row["correct"]
        rows.append(row)
    return rows


def _fixture_runs() -> list[dict]:
    return _entity_type_rows() + _scope_adjustment_rows() + _provenance_rows()


def _imcr_reference_rows() -> list[dict]:
    rows = []
    for index in range(N_ET):
        rows.append(
            {
                "sample_id": f"ET-s{index + 1:02d}",
                "task_type": "entity_type",
                "reference_label": "Event",
                "consensus_tier": "strong_consensus",
            }
        )
    for index in range(N_SA):
        rows.append(
            {
                "sample_id": f"SA-s{index + 1:02d}",
                "task_type": "scope_adjustment",
                "reference_label": "AFTER_BETTER" if index <= 6 else "BEFORE_BETTER",
                "consensus_tier": "strong_consensus",
            }
        )
    for index in range(N_PRV):
        label = "fully_supported" if index < 10 else "insufficient_evidence"
        rows.append(
            {
                "sample_id": f"PRV-s{index + 1:03d}",
                "task_type": "provenance_support",
                "reference_label": label,
                "consensus_tier": "strong_consensus",
            }
        )
    return rows


METHOD_NAMES = {
    "B1_rule_only": "Rule-only",
    "B2_classifier_only": "Frozen classifier",
    "B3_blind_llm": "Blind LLM",
    "B9_agreement_gate": "Rule-model agreement gate",
    "B10_selective_no_gate": "Selective, no structural gate",
    "B12_full_framework": "Full framework",
}


def _write_csv(path: Path, rows: list[dict], fields: list[str]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def _write_runs(path: Path, imcr_style: bool) -> None:
    rows = []
    for row in _fixture_runs():
        new_row = dict(row)
        if imcr_style:
            # Design §2: covered/correct/safe_correct ship as 0 placeholders
            # and are recomputed by the IMCR reference at evaluation time.
            new_row["covered"] = 0
            new_row["correct"] = 0
            new_row["safe_correct"] = 0
        rows.append(new_row)
    _write_csv(path, rows, RUNS_FIELDS)


def _write_judge_files(judge_dir: Path) -> None:
    judge_dir.mkdir(parents=True, exist_ok=True)
    _write_csv(
        judge_dir / rst.JUDGE_PAIRWISE_FILE,
        [
            {"task_type": "t1", "judge_a": "A", "judge_b": "B", "n_compared": 10,
             "n_agree": 8, "agreement": "0.8", "cohens_kappa": "0.6"},
            {"task_type": "t2", "judge_a": "A", "judge_b": "B", "n_compared": 6,
             "n_agree": 3, "agreement": "0.5", "cohens_kappa": "0.1"},
            {"task_type": "t1", "judge_a": "A", "judge_b": "C", "n_compared": 10,
             "n_agree": 5, "agreement": "0.5", "cohens_kappa": "0.2"},
        ],
        ["task_type", "judge_a", "judge_b", "n_compared", "n_agree", "agreement", "cohens_kappa"],
    )
    _write_csv(
        judge_dir / rst.JUDGE_RELIABILITY_FILE,
        [
            {"task_type": "t1", "metric": "n_tasks", "value": "12"},
            {"task_type": "t1", "metric": "n_judges", "value": "3"},
            {"task_type": "t1", "metric": "judges", "value": "A;B;C"},
            {"task_type": "t1", "metric": "fleiss_kappa", "value": "0.2"},
            {"task_type": "t1", "metric": "krippendorff_alpha_nominal", "value": "0.3"},
            {"task_type": "t2", "metric": "n_tasks", "value": "12"},
            {"task_type": "t2", "metric": "n_judges", "value": "3"},
            {"task_type": "t2", "metric": "judges", "value": "A;B;C"},
            {"task_type": "t2", "metric": "fleiss_kappa", "value": "0.4"},
            {"task_type": "t2", "metric": "krippendorff_alpha_nominal", "value": "0.5"},
        ],
        ["task_type", "metric", "value"],
    )
    _write_csv(
        judge_dir / rst.JUDGE_LOJO_FILE,
        [
            {"task_type": "t1", "judge_removed": "A", "n_tasks": 12,
             "n_labeled_full_panel": 5, "n_unchanged_after_removal": 2, "stability": "0.4"},
            {"task_type": "t2", "judge_removed": "A", "n_tasks": 12,
             "n_labeled_full_panel": 5, "n_unchanged_after_removal": 1, "stability": "0.2"},
            {"task_type": "t1", "judge_removed": "B", "n_tasks": 12,
             "n_labeled_full_panel": 5, "n_unchanged_after_removal": 3, "stability": "0.6"},
            {"task_type": "t2", "judge_removed": "B", "n_tasks": 12,
             "n_labeled_full_panel": 5, "n_unchanged_after_removal": 2, "stability": "0.4"},
        ],
        ["task_type", "judge_removed", "n_tasks", "n_labeled_full_panel",
         "n_unchanged_after_removal", "stability"],
    )


def _write_points_outputs(points_dir: Path) -> None:
    """Generate the 13-style outputs with the real experiment-13 machinery.

    The fixture rows are round-tripped through CSV first so the rsi helpers
    see exactly what production sees (stringified flag columns).
    """
    points_dir.mkdir(parents=True, exist_ok=True)
    staged = points_dir / "_staged_runs.csv"
    _write_runs(staged, imcr_style=False)
    runs = rst.read_csv(staged)
    groups: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for row in runs:
        groups[(row["method_id"], row["task_type"])].append(row)
    all_points = []
    for key in sorted(groups):
        rows = groups[key]
        if not any(rsi.numeric_confidence(row) is not None for row in rows):
            continue  # production writes no curve without numeric scores
        all_points.extend(rsi.exact_curve(rows, "constrained_selective"))
    fields = sorted({key for row in all_points for key in row})
    _write_csv(points_dir / rst.POINTS_FILE_SUFFIX, all_points, fields)
    goal13_rows = rsi.goal13_metric_rows(groups, "era", None)
    _write_csv(points_dir / rst.GOAL13_FILE_SUFFIX, goal13_rows, list(goal13_rows[0].keys()))


@pytest.fixture()
def fixture_env(tmp_path: Path) -> dict[str, Path]:
    """Runs (frozen flags), judge files and an IMCR reference, all synthetic."""
    runs_path = tmp_path / "IMCR_BASELINE_RUNS.csv"
    _write_runs(runs_path, imcr_style=False)
    reference_path = tmp_path / "IMCR_REFERENCE_STRONG.csv"
    _write_csv(
        reference_path,
        _imcr_reference_rows(),
        ["sample_id", "task_type", "reference_label", "consensus_tier"],
    )
    judge_dir = tmp_path / "judge"
    _write_judge_files(judge_dir)
    return {
        "runs": runs_path,
        "reference": reference_path,
        "judge_dir": judge_dir,
        "tmp": tmp_path,
    }


def _run_args(env: dict[str, Path], outdir: Path, extra: list[str] | None = None) -> list[str]:
    return [
        "--runs-path", str(env["runs"]),
        "--reference", "frozen",
        "--judge-dir", str(env["judge_dir"]),
        "--output-dir", str(outdir),
        "--bootstrap-replicates", str(N_REPLICATES),
        *(extra or []),
    ]


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


# ---------------------------------------------------------------------------
# Wilson CI table
# ---------------------------------------------------------------------------


def _wilson_formula(k: int, n: int) -> tuple[float, float]:
    """Hand-computed Wilson score interval (z = 1 - (1-0.95)/2 quantile)."""
    z = 1.959963984540054
    p = k / n
    denom = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / denom
    half = (z / denom) * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n))
    return max(0.0, centre - half), min(1.0, centre + half)


def test_wilson_table_endpoints_hand_computed(fixture_env: dict[str, Path]) -> None:
    outdir = fixture_env["tmp"] / "out_wilson"
    rst.main(_run_args(fixture_env, outdir))
    rows = _read_csv(outdir / "WILSON_CI_TABLE.csv")

    coverage_rows = [row for row in rows if row["metric"] == "coverage"]
    accuracy_rows = [row for row in rows if row["metric"] == "selective_accuracy"]
    # 8 cells (5 entity_type methods, 2 scope_adjustment, 1 provenance)
    assert len(coverage_rows) == 8 and len(accuracy_rows) == 8

    def cell(rows_, method, task, metric):
        return next(
            row for row in rows_
            if row["method_id"] == method and row["task_type"] == task and row["metric"] == metric
        )

    # Full framework / entity_type: 14 eligible of 16, 12 correct among them.
    row = cell(coverage_rows, "B12_full_framework", "entity_type", "coverage")
    assert int(row["n"]) == 16 and int(row["correct"]) == 14 and int(row["error"]) == 2
    assert float(row["estimate"]) == pytest.approx(14 / 16)
    low, high = _wilson_formula(14, 16)
    assert float(row["ci95_low"]) == pytest.approx(low, abs=1e-12)
    assert float(row["ci95_high"]) == pytest.approx(high, abs=1e-12)

    row = cell(accuracy_rows, "B12_full_framework", "entity_type", "selective_accuracy")
    assert int(row["n"]) == 14 and int(row["correct"]) == 12
    assert float(row["estimate"]) == pytest.approx(12 / 14)
    low, high = _wilson_formula(12, 14)
    assert float(row["ci95_low"]) == pytest.approx(low, abs=1e-12)
    assert float(row["ci95_high"]) == pytest.approx(high, abs=1e-12)

    # Literature anchor: wilson_ci(25, 100) (statsmodels / R prop.test).
    row = cell(coverage_rows, "B3_blind_llm", "provenance_support", "coverage")
    assert int(row["n"]) == 100 and int(row["correct"]) == 25
    assert float(row["ci95_low"]) == pytest.approx(0.17545211362287674, abs=1e-9)
    assert float(row["ci95_high"]) == pytest.approx(0.34304463548061603, abs=1e-9)
    accuracy = cell(accuracy_rows, "B3_blind_llm", "provenance_support", "selective_accuracy")
    assert int(accuracy["n"]) == 25 and int(accuracy["correct"]) == 10
    low, high = _wilson_formula(10, 25)
    assert float(accuracy["ci95_low"]) == pytest.approx(low, abs=1e-12)

    # Point-only cell (scope_adjustment, no confidence by design §4.3):
    # acceptance = prediction available AND hard gate → all 12 rows accepted.
    row = cell(coverage_rows, "B12_full_framework", "scope_adjustment", "coverage")
    assert row["operating_point_mode"] == "point_only"
    assert int(row["n"]) == 12 and int(row["correct"]) == 12
    low, high = _wilson_formula(12, 12)
    assert float(row["ci95_low"]) == pytest.approx(low, abs=1e-12)
    assert float(row["ci95_high"]) == pytest.approx(1.0, abs=1e-12)
    accuracy = cell(accuracy_rows, "B12_full_framework", "scope_adjustment", "selective_accuracy")
    assert int(accuracy["n"]) == 12 and int(accuracy["correct"]) == 7
    assert "point_only_mode" in accuracy["note"]


# ---------------------------------------------------------------------------
# Paired bootstrap: shared resample indices
# ---------------------------------------------------------------------------


def _packed(scores, corrects, eligible) -> np.ndarray:
    arr = np.zeros(len(scores), dtype=rst._PACKED_DTYPE)
    for position, (score, correct, elig) in enumerate(zip(scores, corrects, eligible)):
        arr[position]["score"] = score
        arr[position]["correct"] = correct
        arr[position]["eligible"] = elig
    return arr


def _entity_type_packed() -> dict[str, np.ndarray]:
    """Per-method packed arrays over the 16-sample entity_type universe."""
    indices = range(N_ET)
    scores = [0.95 - 0.01 * i for i in indices]
    out = {}
    out["B12_full_framework"] = _packed(
        scores, [1 if i <= 11 else 0 for i in indices], [i <= 13 for i in indices]
    )
    out["B1_rule_only"] = _packed(
        scores, [0 if i <= 3 else 1 for i in indices], [True] * N_ET
    )
    out["B2_classifier_only"] = _packed(
        scores, [0 if 6 <= i <= 9 else 1 for i in indices], [True] * N_ET
    )
    return out


def _resample_area(arr: np.ndarray, metric: str, universe_n: int) -> float:
    """Independent re-derivation of the pipeline statistic (metrics.py math)."""
    rows = arr[arr["eligible"]]
    raw = metrics.risk_coverage_curve(rows["score"], rows["correct"])
    ratio = rows.shape[0] / universe_n
    points = [
        metrics.RiskCoveragePoint(
            p.threshold, p.coverage * ratio, p.accepted, p.errors,
            p.selective_risk, p.generalized_risk * ratio, p.safe_coverage * ratio,
        )
        for p in raw
    ]
    return metrics.aurc(points) if metric == "aurc" else metrics.augrc(points)


def test_paired_bootstrap_shares_indices_per_replicate(fixture_env: dict[str, Path]) -> None:
    outdir = fixture_env["tmp"] / "out_paired"
    rst.main(_run_args(fixture_env, outdir))
    replicates = _read_csv(outdir / "PAIRED_BOOTSTRAP_REPLICATES.csv")
    deltas = _read_csv(outdir / "PAIRED_BOOTSTRAP_DELTAS.csv")

    packed = _entity_type_packed()
    full = packed["B12_full_framework"]
    baseline_id = "B1_rule_only"
    base = packed[baseline_id]
    seed = derive_seed(f"paired_bootstrap::entity_type::{baseline_id}")
    assert seed == rst.derive_seed(f"paired_bootstrap::entity_type::{baseline_id}")

    for metric in ("aurc", "augrc"):
        rows = [
            row for row in replicates
            if row["baseline_method_id"] == baseline_id and row["metric"] == metric
        ]
        assert [int(row["replicate_index"]) for row in rows] == list(range(N_REPLICATES))
        assert {int(row["bootstrap_seed"]) for row in rows} == {seed}
        rng = np.random.default_rng(seed)  # identical index stream as the pipeline
        for expected_index, row in enumerate(rows):
            idx = rng.integers(0, N_ET, N_ET)
            full_area = _resample_area(full[idx], metric, N_ET)
            base_area = _resample_area(base[idx], metric, N_ET)
            # Paired property: delta == diff(a, b) on the SAME indices.
            assert float(row["delta"]) == pytest.approx(full_area - base_area, abs=1e-12)
        # The stored point estimate equals the full-data difference.
        delta_row = next(
            row for row in deltas
            if row["baseline_method_id"] == baseline_id and row["metric"] == metric
        )
        expected_estimate = (
            _resample_area(full, metric, N_ET) - _resample_area(base, metric, N_ET)
        )
        assert float(delta_row["estimate"]) == pytest.approx(expected_estimate, abs=1e-12)
        assert float(delta_row["full_estimate"]) == pytest.approx(
            _resample_area(full, metric, N_ET), abs=1e-12
        )
        assert int(delta_row["n_replicates"]) == N_REPLICATES
        assert int(delta_row["n_valid_replicates"]) == N_REPLICATES

    # AURC and AUGRC were bootstrapped on the identical index stream.
    rng_a = np.random.default_rng(seed)
    rng_b = np.random.default_rng(seed)
    for _ in range(N_REPLICATES):
        assert (rng_a.integers(0, N_ET, N_ET) == rng_b.integers(0, N_ET, N_ET)).all()


def test_delta_sign_and_replicate_row_count(fixture_env: dict[str, Path]) -> None:
    outdir = fixture_env["tmp"] / "out_sign"
    rst.main(_run_args(fixture_env, outdir))
    deltas = _read_csv(outdir / "PAIRED_BOOTSTRAP_DELTAS.csv")
    replicates = _read_csv(outdir / "PAIRED_BOOTSTRAP_REPLICATES.csv")

    # Full places its errors last → smaller AURC than B1 (errors first):
    # ΔAURC = Full - B1 must be negative.
    b1_aurc = next(
        row for row in deltas
        if row["task_type"] == "entity_type"
        and row["baseline_method_id"] == "B1_rule_only"
        and row["metric"] == "aurc"
    )
    assert b1_aurc["status"] == "applicable"
    assert float(b1_aurc["estimate"]) < 0.0
    assert float(b1_aurc["ci95_high"]) < 0.0

    # B9 has only two discrete confidence levels → explicit non-applicability,
    # never a silent drop.
    b9 = [row for row in deltas if row["baseline_method_id"] == "B9_agreement_gate"]
    assert {row["status"] for row in b9} == {"not_applicable_insufficient_discrete_points"}
    assert all(row["estimate"] == "" for row in b9)
    # scope_adjustment carries no confidence at all (design §4.3).
    sa = [row for row in deltas if row["task_type"] == "scope_adjustment"]
    assert {row["status"] for row in sa} == {"not_applicable_no_numeric_confidence"}

    # GOAL 13.2: every replicate of every applicable comparison is persisted.
    applicable_pairs = {
        (row["task_type"], row["baseline_method_id"])
        for row in deltas
        if row["status"] == "applicable"
    }
    assert applicable_pairs == {
        ("entity_type", "B1_rule_only"),
        ("entity_type", "B2_classifier_only"),
        ("entity_type", "B10_selective_no_gate"),
    }
    assert len(replicates) == len(applicable_pairs) * 2 * N_REPLICATES
    # B6 is an alias of B2 (design §3): it must never appear as its own row.
    assert not any(row["baseline_method_id"].startswith("B6") for row in deltas)


def test_bootstrap_fixed_seed_reproducible(fixture_env: dict[str, Path]) -> None:
    out1 = fixture_env["tmp"] / "out_repro1"
    out2 = fixture_env["tmp"] / "out_repro2"
    rst.main(_run_args(fixture_env, out1))
    rst.main(_run_args(fixture_env, out2))
    assert (out1 / "PAIRED_BOOTSTRAP_REPLICATES.csv").read_bytes() == (
        out2 / "PAIRED_BOOTSTRAP_REPLICATES.csv"
    ).read_bytes()
    assert (out1 / "WILSON_CI_TABLE.csv").read_bytes() == (
        out2 / "WILSON_CI_TABLE.csv"
    ).read_bytes()


# ---------------------------------------------------------------------------
# McNemar
# ---------------------------------------------------------------------------


def test_mcnemar_b_c_and_exact_p_value(fixture_env: dict[str, Path]) -> None:
    outdir = fixture_env["tmp"] / "out_mcnemar"
    rst.main(_run_args(fixture_env, outdir))
    rows = _read_csv(outdir / "MCNEMAR_TESTS.csv")

    sa = next(
        row for row in rows
        if row["task_type"] == "scope_adjustment"
        and row["baseline_method_id"] == "B3_blind_llm"
    )
    # b = Full correct & B3 wrong = {s4..s7}; c = B3 correct & Full wrong = {s9}.
    assert int(sa["b_full_correct_baseline_wrong"]) == 4
    assert int(sa["c_full_wrong_baseline_correct"]) == 1
    assert int(sa["n_pairs"]) == 12 and int(sa["n_discordant"]) == 5
    # exact binomial: p = 2 * P(X <= 1; n=5, p=.5) = 2 * 6/32 = 0.375
    assert float(sa["p_value"]) == pytest.approx(0.375, abs=1e-12)
    assert sa["method"] == "exact_binomial"
    assert float(sa["statistic"]) == pytest.approx(1.0)
    assert "AFTER_BETTER" in sa["note"]
    assert int(sa["full_wins"]) == 4 and int(sa["full_losses"]) == 1 and int(sa["ties"]) == 7

    # Entity-type comparison with identical correct flags → no discordant
    # pairs; the row is kept with an explicit note (no silent drop).
    b10 = next(
        row for row in rows
        if row["task_type"] == "entity_type"
        and row["baseline_method_id"] == "B10_selective_no_gate"
    )
    assert int(b10["n_discordant"]) == 0
    assert float(b10["p_value"]) == 1.0
    assert "no discordant pairs" in b10["note"]

    # Hand-check the B1 discordances: b = {s1..s4}, c = {s13..s16}.
    b1 = next(
        row for row in rows
        if row["task_type"] == "entity_type" and row["baseline_method_id"] == "B1_rule_only"
    )
    assert int(b1["b_full_correct_baseline_wrong"]) == 4
    assert int(b1["c_full_wrong_baseline_correct"]) == 4
    assert int(b1["n_pairs"]) == 16
    # provenance_support has no Full rows → no comparison (not silently faked)
    assert not any(row["task_type"] == "provenance_support" for row in rows)


# ---------------------------------------------------------------------------
# Judge agreement summary
# ---------------------------------------------------------------------------


def test_judge_summary_pooling_rows(fixture_env: dict[str, Path]) -> None:
    outdir = fixture_env["tmp"] / "out_judge"
    rst.main(_run_args(fixture_env, outdir))
    rows = _read_csv(outdir / "JUDGE_AGREEMENT_SUMMARY.csv")

    kinds = {row["kind"] for row in rows}
    assert kinds == {"pairwise", "reliability", "leave_one_judge_out"}
    all_rows = [row for row in rows if row["task_type"] == "ALL"]
    assert {row["kind"] for row in all_rows} == {
        "pairwise", "reliability", "leave_one_judge_out"
    }

    def all_value(kind, item, metric):
        return next(
            float(row["value"]) for row in all_rows
            if row["kind"] == kind and row["item"] == item and row["metric"] == metric
        )

    # Unweighted means of the published values (no recomputation).
    assert all_value("pairwise", "A_vs_B", "agreement") == pytest.approx((0.8 + 0.5) / 2)
    assert all_value("pairwise", "A_vs_B", "cohens_kappa") == pytest.approx((0.6 + 0.1) / 2)
    assert all_value("reliability", "", "fleiss_kappa") == pytest.approx((0.2 + 0.4) / 2)
    assert all_value("reliability", "", "krippendorff_alpha_nominal") == pytest.approx(0.4)
    assert all_value("reliability", "", "n_tasks") == pytest.approx(24.0)  # counts sum
    assert all_value("leave_one_judge_out", "removed_A", "stability") == pytest.approx(0.3)

    # Per-task rows are carried through verbatim (reference, not recomputation).
    verbatim = next(
        row for row in rows
        if row["kind"] == "reliability" and row["task_type"] == "t1"
        and row["metric"] == "fleiss_kappa"
    )
    assert float(verbatim["value"]) == 0.2


# ---------------------------------------------------------------------------
# IMCR reference mode reuses the experiment-13 semantics
# ---------------------------------------------------------------------------


def test_imcr_reference_recomputation_matches_frozen(fixture_env: dict[str, Path]) -> None:
    outdir = fixture_env["tmp"] / "out_imcr"
    rst.main(
        [
            "--runs-path", str(fixture_env["runs"]),
            "--reference", "imcr_strong",
            "--imcr-strong-path", str(fixture_env["reference"]),
            "--judge-dir", str(fixture_env["judge_dir"]),
            "--output-dir", str(outdir),
            "--bootstrap-replicates", str(N_REPLICATES),
        ]
    )
    frozen_out = fixture_env["tmp"] / "out_frozen_cmp"
    rst.main(_run_args(fixture_env, frozen_out))
    for name in ("WILSON_CI_TABLE.csv", "MCNEMAR_TESTS.csv", "PAIRED_BOOTSTRAP_DELTAS.csv"):
        assert (outdir / name).read_bytes() == (frozen_out / name).read_bytes(), name


# ---------------------------------------------------------------------------
# Cross-check against experiment-13 outputs
# ---------------------------------------------------------------------------


def test_points_crosscheck_passes_on_real_13_machinery(fixture_env: dict[str, Path]) -> None:
    points_dir = fixture_env["tmp"] / "selective_out"
    _write_points_outputs(points_dir)
    outdir = fixture_env["tmp"] / "out_cross"
    result = rst.main(_run_args(fixture_env, outdir, ["--points-dir", str(points_dir)]))
    assert result["crosscheck_status"] == "passed"

    # Without --points-dir the cross-check is explicitly recorded as not requested.
    result_plain = rst.main(_run_args(fixture_env, fixture_env["tmp"] / "out_nocross"))
    assert result_plain["crosscheck_status"] == "not_requested"


def test_points_crosscheck_rejects_mismatch(fixture_env: dict[str, Path]) -> None:
    points_dir = fixture_env["tmp"] / "selective_bad"
    _write_points_outputs(points_dir)
    path = points_dir / rst.POINTS_FILE_SUFFIX
    rows = _read_csv(path)
    # Perturb the accept-all operating point of one cell (the constrained row
    # with the largest accepted_count) — exactly the row the cross-check uses.
    target = max(
        (row for row in rows if row["curve_mode"] == "constrained_selective"),
        key=lambda row: int(row["accepted_count"]),
    )
    target["accepted_count"] = str(int(target["accepted_count"]) - 1)
    _write_csv(path, rows, list(rows[0].keys()))
    with pytest.raises(ValueError, match="cross-check failed"):
        rst.main(
            _run_args(fixture_env, fixture_env["tmp"] / "out_badcross")
            + ["--points-dir", str(points_dir)]
        )


# ---------------------------------------------------------------------------
# Manifest and report
# ---------------------------------------------------------------------------


def test_manifest_inputs_seeds_and_canaries(fixture_env: dict[str, Path]) -> None:
    outdir = fixture_env["tmp"] / "out_manifest"
    rst.main(_run_args(fixture_env, outdir))
    manifest = json.loads((outdir / "STATISTICAL_ANALYSIS_MANIFEST.json").read_text(encoding="utf-8"))
    for field in MANIFEST_FIELDS:
        assert field in manifest
    assert manifest["experiment_id"] == "14_statistical_tests"
    assert manifest["seed"] == 20260907

    runs_digest = hashlib.sha256(fixture_env["runs"].read_bytes()).hexdigest()
    assert manifest["inputs"]["runs"]["sha256"] == runs_digest
    for name in (rst.JUDGE_PAIRWISE_FILE, rst.JUDGE_RELIABILITY_FILE, rst.JUDGE_LOJO_FILE):
        digest = hashlib.sha256((fixture_env["judge_dir"] / name).read_bytes()).hexdigest()
        assert manifest["inputs"][name]["sha256"] == digest

    seed_label = "entity_type::B1_rule_only"
    assert manifest["seed_policy"]["per_pair_seeds"][seed_label] == derive_seed(
        f"paired_bootstrap::{seed_label}"
    )
    assert manifest["bootstrap"]["n_replicates"] == N_REPLICATES
    assert "paired_bootstrap_diff_ci" in manifest["bootstrap"]["implementation"]
    assert manifest["bootstrap"]["per_replicate_output"].startswith(
        "PAIRED_BOOTSTRAP_REPLICATES.csv"
    )
    assert all(manifest["canaries"].values())


def test_report_skeleton_contains_placeholders_and_goal18_sections(
    fixture_env: dict[str, Path],
) -> None:
    outdir = fixture_env["tmp"] / "out_skeleton"
    rst.main(_run_args(fixture_env, outdir))
    report = (outdir / "11_STATISTICAL_ANALYSIS.md").read_text(encoding="utf-8")
    assert rst.PENDING_PLACEHOLDER in report
    for heading in (
        "Wilson",
        "Paired bootstrap",
        "McNemar",
        "Fleiss",
        "Krippendorff",
        "macro-F1",
        "per-class",
    ):
        assert heading in report, heading


def test_report_fill_mode_embeds_numbers(fixture_env: dict[str, Path]) -> None:
    points_dir = fixture_env["tmp"] / "selective_fill"
    _write_points_outputs(points_dir)
    outdir = fixture_env["tmp"] / "out_fill"
    rst.main(_run_args(fixture_env, outdir, ["--points-dir", str(points_dir), "--fill"]))
    report = (outdir / "11_STATISTICAL_ANALYSIS.md").read_text(encoding="utf-8")
    assert rst.PENDING_PLACEHOLDER not in report
    assert "FILLED" in report
    assert "0.17545211362287674" in report  # Wilson(25, 100) low endpoint
    assert "0.375" in report  # exact McNemar p for scope_adjustment vs B3
    assert "macro-F1 on accepted" in report  # section 6 filled from GOAL-13 rows


# ---------------------------------------------------------------------------
# Missing inputs are hard errors
# ---------------------------------------------------------------------------


def test_missing_runs_file_is_a_hard_error(tmp_path: Path) -> None:
    judge_dir = tmp_path / "judge"
    _write_judge_files(judge_dir)
    reference_path = tmp_path / "IMCR_REFERENCE_STRONG.csv"
    _write_csv(
        reference_path,
        _imcr_reference_rows(),
        ["sample_id", "task_type", "reference_label", "consensus_tier"],
    )
    with pytest.raises(FileNotFoundError, match="does not exist"):
        rst.main(
            [
                "--runs-path", str(tmp_path / "NOT_GENERATED_IMCR_BASELINE_RUNS.csv"),
                "--reference", "frozen",
                "--judge-dir", str(judge_dir),
                "--output-dir", str(tmp_path / "out_missing_runs"),
            ]
        )


def test_missing_reference_file_is_a_hard_error(fixture_env: dict[str, Path]) -> None:
    with pytest.raises(FileNotFoundError, match="IMCR"):
        rst.main(
            [
                "--runs-path", str(fixture_env["runs"]),
                "--reference", "imcr_strong",
                "--imcr-strong-path", str(fixture_env["tmp"] / "MISSING_REFERENCE.csv"),
                "--judge-dir", str(fixture_env["judge_dir"]),
                "--output-dir", str(fixture_env["tmp"] / "out_missing_ref"),
            ]
        )
    assert not (fixture_env["tmp"] / "out_missing_ref" / "WILSON_CI_TABLE.csv").exists()


def test_missing_judge_file_is_a_hard_error(fixture_env: dict[str, Path]) -> None:
    judge_dir = fixture_env["tmp"] / "judge_partial"
    judge_dir.mkdir()
    _write_csv(
        judge_dir / rst.JUDGE_PAIRWISE_FILE,
        [{"task_type": "t", "judge_a": "A", "judge_b": "B", "n_compared": 4,
          "n_agree": 2, "agreement": "0.5", "cohens_kappa": "0.0"}],
        ["task_type", "judge_a", "judge_b", "n_compared", "n_agree", "agreement", "cohens_kappa"],
    )
    with pytest.raises(FileNotFoundError, match=r"JUDGE_RELIABILITY_SUMMARY"):
        rst.main(
            [
                "--runs-path", str(fixture_env["runs"]),
                "--reference", "frozen",
                "--judge-dir", str(judge_dir),
                "--output-dir", str(fixture_env["tmp"] / "out_missing_judge"),
            ]
        )


def test_missing_points_file_is_a_hard_error(fixture_env: dict[str, Path]) -> None:
    points_dir = fixture_env["tmp"] / "empty_points"
    points_dir.mkdir()
    with pytest.raises(FileNotFoundError, match=r"RISK_COVERAGE_POINTS"):
        rst.main(
            _run_args(fixture_env, fixture_env["tmp"] / "out_missing_points")
            + ["--points-dir", str(points_dir)]
        )
